ACMM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from two_factor.urls import urlpatterns as tf_urls
from django.conf.urls.static import static

urlpatterns = [
    path('mentorship/', include('mentorship.urls', namespace='mentorship')),
    path(settings.ADMIN_URL + 'admin', admin.site.urls),
    path('', include(tf_urls))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mentorship/urls.py
from django.urls import path
from . import views
from django.contrib.flatpages import views as flat_views
app_name = 'mentorship'
urlpatterns = [
    path('', views.applications_view, name='index'),
    path('mentor/signup', views.mentor_signup_view, name='mentor'),
    path('mentee/signup', views.mentee_signup_view, name='mentee'),
    path('thanks', views.thank_you_view, name='thank_you'),
    path('next_year', views.next_year_view, name='next_year'),
    path('privacy/', flat_views.flatpage, {'url': '/mentorship/privacy/'}, name='privacy')
]

mentorship/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from django_cryptography.fields import encrypt

SEX_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('O', 'Other')
]
ENTRANCE_EXAMS_TYPES = ('BMAT', 'UCAT', 'GAMSAT')
ENTRANCE_EXAM_CHOICES = list(zip(ENTRANCE_EXAMS_TYPES, ENTRANCE_EXAMS_TYPES))
INTERVIEW_EXPERIENCE_CHOICES = [
    ("P", 'Panel'),
    ("M", 'MMI'),
    ('G', 'Group')
]
SPECIALTY_CHOICES = [
    ("PS", 'Personal Statement'),
    ("I", 'Interview'),
    ('EE', 'Entrance Exam'),
    ("WE", 'Work Experience')
]
HEAR_ABOUT_US_CHOICES = [
    ("WM", 'Word of mouth'),
    ("C", 'Contact from ACMM team'),
    ('SM', 'Social Media'),
    ('SU', 'School/University'),
    ("O", 'Other')
]
YEAR_APPLIED_CHOICES = [
    ('A2', 'A level/IB'),
    ('GRAD', 'Graduate')
]
EDUCATION_LEVEL_CHOICES = [
    ("A2", 'A Level'),
    ("AS", 'A/S Level'),
    ('IB', 'International Baccalaureate'),
    ('SH', 'Scottish Highers and Advanced Highers'),
    ("UG", 'Undergraduate'),
    ("M", 'Masters'),
    ("D", 'Doctorate')
]
OCCUPATION_CHOICES = [
    ('MD', 'Doctor'),
    ('D', 'Dentist'),
    ('MS', 'Medical Student'),
    ('DS', 'Dental Student')
]
GRADES = ("A*", "A", "B", "C", "D", "E", "F", "1", "2", "3", "4", "5", "6", "7", "1st", "2:1", "2:2", "3rd")
GRADE_CHOICES = list(zip(GRADES, GRADES))
TRUE_FALSE_CHOICES = [
    (True, 'Yes'),
    (False, 'No')
]
COURSE_CHOICES = [
    ('M', 'Medicine'),
    ('D', 'Dentistry'),
]


class CommonProfileInfo(models.Model):
    """ Common profile info for all applicants."""
    email = encrypt(models.EmailField(max_length=254))
    first_name = encrypt(models.CharField(max_length=30))
    last_name = encrypt(models.CharField(max_length=130))
    sex = encrypt(models.CharField(max_length=1, choices=SEX_CHOICES))
    year_applied = models.CharField(max_length=10, choices=YEAR_APPLIED_CHOICES)
    date_joined = models.DateTimeField(default=timezone.now)
    hear_about_us = models.CharField(max_length=10, choices=HEAR_ABOUT_US_CHOICES, default=None)
    entrance_exam_experience = ArrayField(models.CharField(max_length=10, choices=ENTRANCE_EXAM_CHOICES), default=list)
    interview_experience = ArrayField(models.CharField(max_length=10, choices=INTERVIEW_EXPERIENCE_CHOICES))
    area_of_support = ArrayField(models.CharField(max_length=10, choices=SPECIALTY_CHOICES), default=list)

    class Meta:
        abstract = True


class MentorProfile(CommonProfileInfo):
    """ Profile info for mentor applicants."""
    work_email = encrypt(models.EmailField(max_length=254))
    occupation = models.CharField(max_length=10, choices=OCCUPATION_CHOICES)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.occupation + "-" + str(self.email)

    def get_admin_url(self):
        return reverse("admin:%s_%s_change" % (self._meta.app_label, self._meta.model_name), args=(self.id,))


class MenteeProfile(CommonProfileInfo):
    """ Profile info for mentee applicants."""
    mentor_need = models.TextField(null=True, blank=True)
    mentor_help = models.TextField(null=True, blank=True)
    mentor_relationship = models.TextField(null=True, blank=True)
    course = models.CharField(max_length=10, choices=COURSE_CHOICES)
    current_application = models.BooleanField(default=True, choices=TRUE_FALSE_CHOICES)
    accepted = models.BooleanField(default=False, choices=TRUE_FALSE_CHOICES)
    mentor = models.ForeignKey(MentorProfile, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.course + "-" + str(self.email)


class CommonQualificationInfo(models.Model):
    """Common atributes of a qualification"""
    name = models.CharField(max_length=50)
    education_level = models.CharField(max_length=10, choices=EDUCATION_LEVEL_CHOICES)

    class Meta:
        abstract = True

    def __str__(self):
        return self.education_level + "-" + self.name


class MenteeQualification(CommonQualificationInfo):
    """Mentee type Qualifications model"""
    grade = models.CharField(max_length=10, choices=GRADE_CHOICES)
    predicted = models.BooleanField(default=False, choices=TRUE_FALSE_CHOICES)
    profile = models.ForeignKey(MenteeProfile, on_delete=models.CASCADE)


class MentorQualification(CommonQualificationInfo):
    """Mentor type Qualifications model"""
    profile = models.ForeignKey(MentorProfile, on_delete=models.CASCADE)

mentorship/forms.py
from django import forms
from django.utils.html import format_html
from . import models


class MentorForm(forms.ModelForm):
    area_of_support = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=models.SPECIALTY_CHOICES,
        label="What area can you provide support in?")
    interview_experience = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=models.INTERVIEW_EXPERIENCE_CHOICES,
        label="What interview experience do you have?")
    entrance_exam_experience = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        choices=models.ENTRANCE_EXAM_CHOICES,
        label="What exam experience do you have?",
        required=False)

    honeypot = forms.CharField(widget=forms.HiddenInput(), required=False)
    tcs_check = forms.BooleanField(required=True, label=format_html(
        '''I have read and agree to the <a href="{}">Privacy Policy</a> ''', '/mentorship/privacy/'))

    class Meta:
        model = models.MentorProfile
        exclude = ['is_active', 'date_joined']
        labels = {
            'year_applied': 'Qualification level prior to studying Medicine/Dentistry',
            'hear_about_us': 'How did you hear about us?'
        }
        help_texts = {
            'email': 'Email to be contacted regarding mentorship.',
            'work_email': 'Email to verify work/study status.'
        }


class MentorQualificationForm(forms.ModelForm):
    class Meta:
        model = models.MentorQualification
        exclude = ['profile']


class MenteeForm(forms.ModelForm):
    area_of_support = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=models.SPECIALTY_CHOICES,
        label="What do you need help with?")

    entrance_exam_experience = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=models.ENTRANCE_EXAM_CHOICES,
        label="What entrance exam experience have you had?",
        required=False)

    interview_experience = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=models.INTERVIEW_EXPERIENCE_CHOICES,
        label="What interview experience have you had?",
        required=False)

    current_application = forms.ChoiceField(
        choices=models.TRUE_FALSE_CHOICES,
        label="Are you applying this year?",
        help_text="Our mentor scheme is for students applying to Medicine/Dentistry this year only"
    )

    mentor_need = forms.CharField(widget=forms.Textarea(attrs={
        'rows': '5',
        'cols': '90',
        'maxlength': '500',
    }),
        label="Why do you want a mentor and what do you hope to gain ?",
        help_text="Max 500 Characters")

    mentor_help = forms.CharField(widget=forms.Textarea(attrs={
        'rows': '5',
        'cols': '90',
        'maxlength': '500',
    }),
        label="How will a mentor help with your application?",
        help_text="Max 500 Characters")

    mentor_relationship = forms.CharField(widget=forms.Textarea(attrs={
        'rows': '5',
        'cols': '90',
        'maxlength': '500',
    }),
        label="How will you go about fostering a good relationship your mentor?",
        help_text="Max 500 Characters")

    honeypot = forms.CharField(widget=forms.HiddenInput(), required=False)
    tcs_check = forms.BooleanField(required=True, label=format_html(
        '''I have read and agree to the <a href="{}">Privacy Policy</a> ''', '/mentorship/privacy'))

    class Meta:
        model = models.MenteeProfile
        exclude = ['date_joined', 'assigned_mentor', 'accepted']
        labels = {
            'year_applied': 'What is your current education level?',
            'hear_about_us': 'How did you hear about us?'
        }


class MenteeQualificationForm(forms.ModelForm):
    predicted = forms.ChoiceField(choices=models.TRUE_FALSE_CHOICES, required=True, label="Predicted ?")

    class Meta:
        model = models.MenteeQualification
        exclude = ['profile']


# TODO:Add tests
MenteeQualificationFormSet = forms.inlineformset_factory(
    models.MenteeProfile,
    model=models.MenteeQualification,
    form=MenteeQualificationForm,
    extra=2,
    min_num=1,
    max_num=10,
    validate_min=True,
    validate_max=True)

MentorQualificationFormSet = forms.inlineformset_factory(
    models.MentorProfile,
    model=models.MentorQualification,
    form=MentorQualificationForm,
    extra=2,
    min_num=1,
    max_num=10,
    validate_min=True,
    validate_max=True)

mentorship/views.py
from django.shortcuts import render, redirect
from . import forms


def thank_you_view(request):
    return render(request, 'mentorship/thank_you.html', {'page_title': 'Thank You'})


def next_year_view(request):
    return render(request, 'mentorship/next_year.html', {'page_title': 'Apply Next Year'})


def applications_view(request):
    return render(request, 'mentorship/applications.html', {'page_title': 'ACMM Application Portal'})


def mentor_signup_view(request):
    if request.method == "POST":
        form = forms.MentorForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['honeypot']:
                return redirect('mentorship:thank_you')
            profile = form.save(commit=False)
            formset = forms.MentorQualificationFormSet(request.POST, request.FILES, instance=profile)
            if formset.is_valid():
                form.save()
                formset.save()
                return redirect('mentorship:thank_you')
        else:
            formset = forms.MentorQualificationFormSet(request.POST, request.FILES)
    else:
        form = forms.MentorForm()
        formset = forms.MentorQualificationFormSet()
    return render(request, 'mentorship/mentor_signup.html',
                  {'page_title': 'Mentor Application', "form": form, "qualification_formset": formset})


def mentee_signup_view(request):
    if request.method == "POST":
        form = forms.MenteeForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['honeypot']:
                return redirect('mentorship:thank_you')
            if form.cleaned_data['current_application'] == "False":
                return redirect('mentorship:next_year')
            profile = form.save(commit=False)
            formset = forms.MenteeQualificationFormSet(request.POST, request.FILES, instance=profile)
            if formset.is_valid():
                form.save()
                formset.save()
                return redirect('mentorship:thank_you')
        else:
            formset = forms.MenteeQualificationFormSet(request.POST, request.FILES)
    else:
        form = forms.MenteeForm()
        formset = forms.MenteeQualificationFormSet()
    return render(request, 'mentorship/mentee_signup.html',
                  {'page_title': 'Mentee Application', "form": form, "qualification_formset": formset})

mentorship/templates/mentorship/applications.html
{% extends 'mentorship/base.html' %} {% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Welcome to the ACMM Application Portal!</h1>
        <p class="lead">Dear mentors and mentees, welcome to our mentoring scheme this coming year. This is our 6th year
            of helping
            African Caribbean prospective medical and dental students achieve their dreams with mentoring on a 1 to 1
            basis during the course of UCAS applications.
            <br/>
            <br/>
            ACMM started after identifying the need to have more black students represented in medical school and
            therefore within the profession. On our journey into and during medical school, we found a lack of support
            for black students, combined with a lack of representation within the field. This was backed up by various
            statistics that demonstrate our underrepresentation in Medicine and Dentistry. We therefore co- founded ACMM
            to help further the chances of prospective Afro-Caribbean students into medical school, to realise the
            potential of these students and to encourage future applicants to think about a career in medicine.
            <br/>
            <br/>
            What does the ACMM mentoring scheme involve?
            <br/>
            <br/>
            As a mentor you will be matched with one mentee, who you will support for a year – from June until June of the
            next year.
            You will support your mentee in their medical school application by providing help and advice on entrance
            exams, personal statements and hopefully interview preparation. We will try and match you with a mentee who
            has similar personal characteristics to you in order to make the mentoring relationship as beneficial as
            possible. You will commit to monthly contact as a bare minimum, with more contact and support given in the
            summer prior to application.
            <br/>
            <br/>
        </p>
        <p class="lead">How ACMM will support mentors and mentees:</p>
        <ul class="lead">
            <li>Provision of interview and personal statement guides to support your mentee</li>
            <li>Continuing to be available by email/social media if you have any difficulties</li>
            <li>Monthly emails reminding you to contact your mentor/mentee, with relevant topics to guide discussions
            </li>
            <li>A mentor brief to further understand your role as a mentor</li>
            <li>A mentor checklist to ensure you have supported your mentee for all the important topics</li>
        </ul>
        <br/>
        <br/>
        <p class="lead">You can contact us at any time through the following avenues:</p>
        <ul class="lead">
            <li>Twitter: @ACMM</li>
            <li>LinkedIn: African Caribbean Medical Mentors</li>
            <li>Email: mentoring@acmedicalmentors.co.uk
            </li>
            <li>Website contact forms: www.acmedicalmentors.co.uk</li>
        </ul>
        <p class="lead">Thank you for your interest in ACMM.Please complete select which application you would like to
            complete.</p>
        <hr class="my-4">
        <p>Please note that we will only accept one application per an applicant. </p>
        <p>ACMM applications are very competitive so prior to submission please ensure questions are answered and all
            details are accurate. </p>
        <p>If you are interested our schemes or just want to find out more please go to our website. </p>
        <p class="lead">
            <a class="btn btn-secondary btn-lg" href="{% url 'mentorship:mentor' %}" role="button">Mentor Sign-Up</a>
            <a class="btn btn-secondary btn-lg" href="{% url 'mentorship:mentee' %}" role="button">Mentee Sign-Up</a>
        </p>
    </div>
{% endblock %}

mentorship/templates/mentorship/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
            crossorigin="anonymous"
    />
    <link rel="shortcut icon" type="image/png" href="{% static 'mentorship/images/favicon.png' %}"/>
    <title>
        {{ page_title }}
    </title>
</head>
<body class="bg-light min-vh-100" >
<img src="{% static 'mentorship/images/favicon.png' %}" width="300" height="300"/>
<div class="container p-5">{% block content %} {% endblock %}</div>
</body>
<footer class="text-center text-white page-footer">
    <!-- Copyright -->
    <div class="text-center text-white p-3 bg-secondary">
        © 2023 Copyright:
        <a class="text-white" href="https://www.acmedicalmentors.co.uk/">African Caribbean Medical Mentors </a> | ALL RIGHTS RESERVED |
     Registered charity number: 1190968
    </div>
</footer>
</html>

mentorship/templates/mentorship/mentee_signup.html
{% extends 'mentorship/base.html' %} {% load crispy_forms_tags %} {% block content %}{% load static %}
    <div class="mb-2 bg-white text-dark rounded">
        <div class="p-3 bg-secondary text-white rounded">
            <h1>Mentee SignUp</h1>
            <p>
                <br/>
Should you be successful, you will be matched with a mentor by the 15th June 2023.
                <br/>
                This commitment is for one year.
                <br/>
                If you require more information, please see our
                <strong
                ><a href="//www.acmedicalmentors.co.uk/mentoring" class="text-white">
                    website</a
                >:</strong
                >
            </p>
        </div>
        <form id="profile-form" method="post">
            {% csrf_token %}
            <div class="p-3">
                <h4>Personal Information</h4>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-10 mb-0">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.sex|as_crispy_field }}
                    </div>
                </div>
                <hr class="my-4"/>
                <h4>Background Information</h4>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.course|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.current_application|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.year_applied|as_crispy_field }}
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.entrance_exam_experience|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.interview_experience|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.area_of_support|as_crispy_field }}
                    </div>
                </div>

                {{ form.mentor_need|as_crispy_field }}
                {{ form.mentor_help|as_crispy_field }}
                {{ form.mentor_relationship|as_crispy_field }}
            </div>

            <div id="qualification-container">
                <h5 class="p-3">Qualification(s)</h5>
                {{ qualification_formset.management_form |crispy }}
                {% for form in qualification_formset %}
                    <div class="form-row qualification-form p-3">
                        <div class="form-group col-md-3 mb-0">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-3 mb-0">
                            {{ form.education_level|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{ form.grade|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-3 mb-0">
                            {{ form.predicted|as_crispy_field }}
                        </div>

                        <button
                                class="align-self-center btn btn-outline-danger btn-xs delete-qualification-form"
                                type="button"
                        >
                            Delete
                        </button>
                    </div>
                {% endfor %}
            </div>
            <div class="form-row p-3">
                <button
                        id="add-qualification-form"
                        class="align-middle btn btn-outline-secondary"
                        type="button"
                >
                    Add Another Qualification
                </button>
            </div>
            <div class="form-row p-3">{{ form.hear_about_us|as_crispy_field }}</div>
            <div class="form-row p-3">{{ form.tcs_check|as_crispy_field }}</div>
            <div class="form-row p-3">
                <button id="signup" type="submit" class="btn btn-secondary btn-lg">Sign Up!</button>
            </div>
            {{ form.honeypot|as_crispy_field }}
        </form>
    </div>
    <script src="{% static 'mentorship/js/QualificationFormset.js' %}"></script>
{% endblock %}

mentorship/templates/mentorship/mentor_signup.html
{% extends 'mentorship/base.html' %} {% load crispy_forms_tags %} {% block content %}{% load static %}
    <div class="mb-2 bg-white text-dark rounded">
        <div class="p-3 bg-secondary text-white rounded-top">
            <h1>Mentor Sign-Up</h1>
            <p>
                <br/>
                This commitment is for one year.
                <br/>
                If you require more information, please see our
                <strong
                ><a href="//www.acmedicalmentors.co.uk/mentoring" class="text-white">
                    website</a
                >:</strong
                >
            </p>
        </div>
        <form id="profile-form" method="post">
            {% csrf_token %}
            <div class="p-3">
                <h4>Personal Information</h4>
                <div class="form-row">
                    <div class="form-group col-md-5 mb-0">
                        {{ form.first_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-5 mb-0">
                        {{ form.last_name|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-2 mb-0">
                        {{ form.sex|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.work_email|as_crispy_field }}
                    </div>
                </div>

                <hr class="my-4"/>

                <h4>Background Information</h4>
                <div class="form-row">
                    <div class="form-group col-md-6 mb-0">
                        {{ form.occupation|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-6 mb-0">
                        {{ form.year_applied|as_crispy_field }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4 mb-0">
                        {{ form.entrance_exam_experience|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.interview_experience|as_crispy_field }}
                    </div>
                    <div class="form-group col-md-4 mb-0">
                        {{ form.area_of_support|as_crispy_field }}
                    </div>
                </div>
            </div>

            <div id="qualification-container">
                <h5 class="p-3">Qualification(s)</h5>
                {{ qualification_formset.management_form |crispy }}
                <p class="text-danger">
                    {% for error in qualification_formset.errors %}
                        <small>{{ error }}</small>
                    {% endfor %}
                </p>
                {% for form in qualification_formset %}
                    <div class="form-row qualification-form p-3">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.education_level|as_crispy_field }}
                        </div>
                        <button
                                class="align-self-center btn btn-outline-danger btn-xs delete-qualification-form"
                                type="button"
                        >
                            Delete
                        </button>
                    </div>
                {% endfor %}
            </div>
            <div class="form-row p-3">
                <button
                        id="add-qualification-form"
                        class="align-middle btn btn-outline-secondary"
                        type="button"
                >
                    Add Another Qualification
                </button>
            </div>
            <div class="form-row p-3">{{ form.hear_about_us|as_crispy_field }}</div>
            <div class="form-row p-3">{{ form.tcs_check|as_crispy_field }}</div>
            <div class="form-row p-3">
                <button id="signup" type="submit" class="btn btn-secondary btn-lg">Join Us !</button>
            </div>
            {{ form.honeypot|as_crispy_field }}

        </form>
    </div>

    <script src="{% static 'mentorship/js/QualificationFormset.js' %}"></script>
{% endblock %}

mentorship/templates/mentorship/next_year.html
{% extends 'mentorship/base.html' %} {% block content %}
<div class="jumbotron">
    <h1 class="display-4">Thank You!</h1>
    <p class="lead">Thank you for your interest in ACMM however due to high volume of applications we must prioritize applicants applying this year.We hope to hear from you soon next year.</p>
    <hr class="my-4">
    <p>If you are interested our schemes or just want to find out more please go to our website. </p>
    <p class="lead">
      <a class="btn btn-secondary btn-lg" href="https://www.acmedicalmentors.co.uk/" role="button">Learn more</a>
    </p>
  </div>
{% endblock %}

mentorship/templates/mentorship/thank_you.html
{% extends 'mentorship/base.html' %} {% block content %}
<div class="jumbotron">
    <h1 class="display-4">Thank You!</h1>
    <p class="lead">Thank you for completing an ACMM application.</p>
    <hr class="my-4">
    <p>We will now review the application and contact you.If you are interested our schemes or just want to find out more please go to our website. </p>
    <p class="lead">
      <a class="btn btn-secondary btn-lg" href="https://www.acmedicalmentors.co.uk/" role="button">Learn more</a>
    </p>
  </div>

{% endblock %}